### ISSUE TITLE
Schedule does not generate for VISA 340, ARTH 300, VISA 310

### ISSUE THREAD

**Issue by gbvivian** [gbvivian/schedulecreator#26]

**Comment by nickwu241** [comment]
`VISA 310` `VISA 340` activity types were `Studio`
`ARTH 300` activity type was `Seminar`

Added support to return those type + `Lecture`.

**Comment by gbvivian** [comment]
Fixed! 
![del](https://user-images.githubusercontent.com/17520798/31597409-083f9a9e-b1fd-11e7-8178-862461f11953.png)
